---
apiVersion: v1
kind: Secret
metadata:
  name: signing-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "tekton_chains.labels" . | indent 4 }}
    pipeline.tekton.dev/release: "devel"
    version: {{ .Chart.AppVersion }}

# The data is populated at install time.
# data:
