apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "tekton_pipelines.fullname". }}-info
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "tekton_pipelines.labels" . | indent 4 }}
subjects:
  # Giving all system:authenticated users the access of the
  # ConfigMap which contains version information.
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "tekton_pipelines.fullname". }}-info
