kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "tekton_pipelines.fullname". }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "watch"]
  # The webhook needs access to these configmaps for logging information.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
    resourceNames: ["{{ template "tekton_pipelines.fullname". }}-logging", "{{ template "tekton_pipelines.fullname". }}-observability", "{{ template "tekton_pipelines.fullname". }}-leader-election", "{{ template "tekton_pipelines.fullname". }}-feature-flags"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch"]
  # The webhook daemon makes a reconciliation loop on webhook-certs. Whenever
  # the secret changes it updates the webhook configurations with the certificates
  # stored in the secret.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
    resourceNames: ["{{ template "tekton_pipelines.fullname". }}-webhook-certs"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["{{ template "tekton_pipelines.fullname". }}"]
    verbs: ["use"]
