apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tekton_pipelines.fullname". }}-webhook-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}
    pipeline.tekton.dev/release: {{ .Chart.AppVersion | quote }}

# The data is populated at install time.
