apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tekton_pipelines.fullname". }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}
